name: On Push Event Workflow — DEV Environment — API Regression

on:
  push:
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore SOC-backend/SOC-backend.sln

      - name: Build
        run: dotnet build SOC-backend/SOC-backend.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test SOC-backend/SOC-backend.sln --configuration Release --no-build --collect:"XPlat Code Coverage" --results-directory ./test-results

      - name: Publish Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: /home/runner/work/SOC-Backend/SOC-Backend/test-results/*/coverage.cobertura.xml
