name: Deploy backend to Luna server

on: 
  push: 
    branches: [ main ]

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: | 
          dotnet restore SOC-backend/SOC-backend/SOC-backend.api/SOC-backend.api.csproj
          dotnet restore SOC-backend/SOC-backend/SOC-backend.logic/SOC-backend.logic.csproj
          dotnet restore SOC-backend/SOC-backend/SOC-backend.data/SOC-backend.data.csproj

      - name: Build project
        run: | 
          dotnet build SOC-backend/SOC-backend/SOC-backend.api/SOC-backend.api.csproj --configuration Release --no-restore
          dotnet build SOC-backend/SOC-backend/SOC-backend.logic/SOC-backend.logic.csproj --configuration Release --no-restore
          dotnet build SOC-backend/SOC-backend/SOC-backend.data/SOC-backend.data.csproj --configuration Release --no-restore

      - name: Publish the project
        run: dotnet publish SOC-backend/SOC-backend/SOC-backend.api/SOC-backend.api.csproj --configuration Release --runtime win-x64 --output ./publish --self-contained false --no-build

      - name: Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.LUNA_SERVER }}
          username: ${{ secrets.LUNA_USERNAME }}
          password: ${{ secrets.LUNA_PASSWORD }}
          local-dir: ./publish/
          server-dir: ${{ secrets.LUNA_DIR }}
          protocol: ftps
      
      
      
      
