name: Docker Image build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: login to docker hub  
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ivarot/sagaofcards-backend:latest
  deploy:
    needs: build
    runs-on: self-hosted  # This will run on your self-hosted runner
    steps:
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Pull latest Docker image
        run: docker pull sagaofcards-backend:latest

      - name: Stop and remove old Docker container (if exists)
        run: |
          docker stop sagaofcards-backend || true
          docker rm sagaofcards-backend || true

      - name: Run new Docker container
        run: |
          docker run -d --name sagaofcards-backend -p 80:80 sagaofcards-backend:latest
    
