name: Run E2E tests and upload screenshots

on:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['main']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Setup selenium/standalone-chrome
        run: docker run -d -p 4444:4444 -p 7900:7900 --shm-size="2g" selenium/standalone-chrome:latest

      - name: Restore
        run: dotnet restore SOC-backend/SOC-backend.sln

      - name: Build Docker image 
        run: docker build --build-arg ASPNETCORE_ENVIRONMENT=Testing -t sagaofcards:${{ github.sha }} .

      - name: Run Docker container 
        run: docker run -d -p 8080:8080 --env ASPNETCORE_ENVIRONMENT=Testing --name sagaofcards-container sagaofcards:${{ github.sha }}

      - name: Health check
        run: | 
          echo "Waiting for healthy response.."
          while ! curl -sSf http://localhost:8080/health; do
            sleep 5
          done

      - name: E2E SignUp tests
        run: dotnet test SOC-backend/SOC-backend.sln --filter "TestCategory=E2E-SignUp"

      - name: E2E Login tests
        if: always()
        run: dotnet test SOC-backend/SOC-backend.sln --filter "TestCategory=E2E-Login"

      - name: Check container logs
        if: always()
        run: docker logs sagaofcards-container

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: /home/runner/work/SOC-Backend/screenshots
