name: Run E2E tests and upload screenshots

on:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run docker-compose
        run: docker-compose up --build -d

      - name: Health check
        run: |
          echo "Waiting for healthy response.."
          timeout 2m bash -c 'while ! curl -sSf http://localhost:8080/health; do sleep 5; done'

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Run E2E tests
        run: dotnet test SOC-backend/SOC-backend.sln --filter "TestCategory=E2E" 

      - name: Check container logs
        if: always()
        run: docker-compose logs

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: /home/runner/work/SOC-Backend/screenshots
