name: Run tests and generate report

on:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['main']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
    
      - name: Restore
        run: dotnet restore SOC-backend/SOC-backend.sln

      - name: Build
        run: dotnet build SOC-backend/SOC-backend.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test SOC-backend/SOC-backend.sln --configuration Release --no-build --collect:"XPlat Code Coverage" --results-directory ./test-results --filter "TestCategory!=E2E"

      - name: Run selenium chrome docker
        run: docker run -d -p 4444:4444 -p 7900:7900 --shm-size="2g" selenium/standalone-chrome:latest

      - name: E2E tests
        run: dotnet test SOC-backend/SOC-backend.sln --filter "TestCategory==E2E"
        
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: /home/runner/work/SOC-Backend/SOC-Backend/SOC-backend/SOC-backend.test/TestResults/*/coverage.cobertura.xml
          base_commit: ${{ github.event.pull_request.base.sha }}
