# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore SOC-backend/SOC-backend.sln

    - name: Install local tools
      run: dotnet tool restore
      
    - name: Build
      run: dotnet build SOC-backend/SOC-backend.sln --no-restore
      
    - name: Test
      run: dotnet test SOC-backend/SOC-backend.sln --no-build --verbosity normal --collect:"XPlat Code Coverage"

    - name: Generate Code Coverage Report
      run: dotnet tool run reportgenerator -reports:**/coverage.cobertura.xml -targetdir:coverage-report -reporttypes:Html

    -  name: Upload Coverage Report
       uses: actions/upload-artifact@v3
       with:
        name: code-coverage-report
        path: coverage-report
